---
title: "EDA"
author: "Pablo Benavides-Herrera"
date: 2020-06-09
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    theme: united
    highlight: tango
---

```{r pkgs, message=FALSE}
library(tidyverse)
library(moderndive)
library(patchwork)
```


```{r}
house_prices
glimpse(house_prices)

house_prices <- house_prices %>% 
  mutate(log10_price = log10(price),
         log10_size = )
```

```{r}
p1 <- ggplot(house_prices, aes(x = price)) + geom_histogram(binwidth = 200000, color="white") +
  labs(x = "price (USD)", title = "House price")
p1 
```


```{r}
p2 <- ggplot(house_prices, aes(x = sqft_living)) + geom_histogram(binwidth = 500, fill = "orange", color="white") +
  labs(x = "living space (square feet)", title = "House size")
p2
```

```{r}
p3 <- ggplot(house_prices, aes(x = condition)) +
  geom_bar(aes(fill=condition)) +
  labs(x = "condition", title = "House condition") +
  theme(legend.position = "none")
p3
```
All the plots together with `patchwork`

```{r}
(p1 + p2)/  p3
```


```{r}
p1new <- ggplot(house_prices, aes(x = price*21)) +
  geom_histogram(binwidth = 4000000, fill = 'gray', color = 'white') +
  labs (x = 'price(MXN)', title = ' House price')
 
p2new <- ggplot(house_prices, aes(x = sqft_living* 0.092903)) +
  geom_histogram(binwidth= 40, fill = 'orange', color = 'white') +
  labs (x = 'Squared Meters', title = ' House size')
 
(p1new + p2new)/  p3
```


# Summary statistics

```{r}
house_prices %>% 
  summarize(mean_price = mean(price*21),
          median_price = median(price*21),
          sd_price = sd(price*21))
```

```{r}
house_prices %>% 
  summarize(mean_mts_living = mean(sqft_living* 0.092903),
          median_mts_living = median(sqft_living* 0.092903),
          sd_price_mts_living = sd(sqft_living* 0.092903))
```

```{r}
house_prices_new <- house_prices %>% 
  mutate(log10_price = log10(price*21),
         log10_size = log10(sqft_living*0.092903))
glimpse(house_prices_new)
```

```{r}
house_prices_new %>% 
  select(log10_price,  log10_size)
```

```{r}
p_before <- ggplot(house_prices_new, aes(x = price*21)) + 
  geom_histogram(binwidth = 4000000, fill = 'black', color = 'white') + 
  labs (x = 'price(MXN)', title = ' House price: Before')
p_after <- ggplot(house_prices_new, aes(x = log10_price)) + 
  geom_histogram(bins = 40, fill = 'dodgerblue', color = 'white') + 
  labs (x = 'price(MXN)', title = ' House price: After (log scale)')
p_before + p_after
```

```{r}
p_before_mts <- ggplot(house_prices_new, aes(x = sqft_living*0.092903)) + 
  geom_histogram(bins=50,fill = 'black', color = 'white') + 
  labs (x = 'size mts', title = ' House size: Before')
p_after_mts <- ggplot(house_prices_new, aes(x = log10_size)) + 
  geom_histogram(bins = 40, fill = 'brown', color = 'white') + 
  labs (x = 'size mts', title = ' House size: After (log scale)')
p_before_mts + p_after_mts
```

```{r}
(p_after + p_after_mts) / p3
```

```{r}
ggplot(house_prices_new, aes(x = log10_size, y = log10_price, color = condition)) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(title = "House prices in Seattle") +
  facet_wrap(~condition)
```
# Modeling 

```{r}
ggplot(house_prices_new, aes(x = log10_size, y = log10_price, color = condition)) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(title = "House prices in Seattle")
```

```{r}
ggplot(house_prices_new, aes(x = log10_size, y = log10_price, color = condition)) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(title = "House prices in Seattle") + 
  facet_wrap(~condition)
```


```{r}
ggplot(house_prices_new, aes(x = log10_size, y = log10_price, color = condition)) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(title = "House prices in Seattle") + 
  facet_wrap(~condition) +
  geom_smooth(method = "lm")
```


Fit - Regression model

```{r}
price_prediction <- lm(log10_price ~ log10_size * condition, data = house_prices_new)
parameters <- get_regression_table(price_prediction)
parameters
```
Hacer predicciones. 

```{r}
params <- parameters$estimate
params
```


```{r}
params <- parameters$estimate
prediction <- function(params, size, indx) {
output <- if(indx == 1) params[1] + params[2] *log10(size) else (params[1] + params[1+indx]) +  (params[2] + params[5+indx]) *log10(size)
return(10^(output)) # going back to pesos
}
prediction(params, 100, 3)
```

# Actividad

