---
title: "Text mining Jane Austen's Books"
subtitle: "Lecture 6"
author: "Pablo Benavides-Herrera"
date: 2020-06-18
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    theme: flatly
    highlight: tango
---

Las paqueterías a utilizar.

```{r, message=FALSE}
library(tidyverse)
library(janeaustenr)
library(tidytext)
```

Se sigue el ejemplo mostrado [aquí](https://www.tidytextmining.com/tfidf). Otro ejemplo se puede mostrar [aquí](https://www.tidytextmining.com/tidytext.html#tidyausten).



```{r}
book_words <- austen_books() %>%
  unnest_tokens(word, text) %>%
  count(book, word, sort = TRUE)

total_words <- book_words %>% 
  group_by(book) %>% 
  summarize(total = sum(n))

book_words <- left_join(book_words, total_words)

book_words
```


```{r}
ggplot(book_words, aes(n/total, fill = book)) +
  geom_histogram(show.legend = FALSE) +
  xlim(NA, 0.0009) +
  facet_wrap(~book, ncol = 2, scales = "free_y")
```


```{r}
freq_by_rank <- book_words %>% 
  group_by(book) %>% 
  mutate(rank = row_number(), 
         `term frequency` = n/total)

freq_by_rank
```


```{r}
freq_by_rank %>% 
  ggplot(aes(rank, `term frequency`, color = book)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
```




```{r}
book_words <- book_words %>%
  bind_tf_idf(word, book, n)

book_words
```


```{r}
book_words %>%
  select(-total) %>%
  arrange(desc(tf_idf))
```



```{r}
book_words %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  group_by(book) %>% 
  top_n(15) %>% 
  ungroup() %>%
  ggplot(aes(word, tf_idf, fill = book)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~book, ncol = 2, scales = "free") +
  coord_flip()
```



