---
title: "K-Means"
subtitle: "Color extraction from images"
author: "Pablo Benavides Herrera"
date: 2020-06-23
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Extracting dominant colours from pictures

```{r}
#install.packages("imager")
library(imager)
library(patchwork)
file <- "autumn_drawing_walking_82963_320x480.jpg"
#file
im <- load.image(file)
plot(im, axes = FALSE)
#file
```

```{r}
library(tidyverse)
bdf <- as.data.frame(im, wide="c")
bdf
```
```{r}
rgb(0.20,0.21,0.58)
```

```{r}
ggplot(data.frame(x = 0, y = 0), aes(x, y)) + 
  geom_point(size = 25,  color = "#333694")

```
```{r}
data.frame(x =0, y = 0)
```

```{r}
x = c(0, 0, 0) 
y = c(0, 1, 2) 
df = data.frame(x, y) 
df
```
```{r}
ggplot(df, aes(x, y)) + 
  geom_point(size = 25,  color = "#333694")
```

```{r}
kclust <- kmeans(bdf, centers = 5)
kclust
```

```{r}
k_means <- kclust$centers %>%
  as_tibble() %>% 
  select(-c(x,y))
show_col(rgb(k_means), labels=FALSE, ncol = 1)
```

```{r}
plot(im, axes = FALSE) + show_col(rgb(k_means), labels=FALSE, ncol = 1)
```


```{r}
tidy(kclust)
colores <- tidy(kclust) %>% 
  select(x3:x5) %>% rgb()
```
```{r}
tibble(x = c(rep(0,5)),
       y = c(1,3,5,7,9),
       k = factor(1:5)) %>% 
  ggplot(aes(x,y)) +
  geom_point(size = 20, color = colores)+
  coord_cartesian(xlim = c(-5,.05), ylim = c(-0.3,10))+
  theme_void()+
  theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
  ) +
  annotation_custom(rasterGrob(im),xmin = -Inf, xmax = Inf,
                    ymin = -Inf, ymax = Inf)
```

